blank_issues_enabled: false
contact_links:
  - name: 提问
    url: https://github.com/hongggggv/Tianyicraft/discussions/categories/%E6%8F%90%E9%97%AE
    about: 我对 Tianyicraft 有些疑问...
  - name: 讨论
    url: https://github.com/hongggggv/Tianyicraft/discussions/categories/%E8%AE%A8%E8%AE%BA
    about: 我想讨论有关 Tianyicraft 有关的话题...
