name: "优化 "
description: 一些好的优化都可以留下！
title: "[优化] "
labels: [优化]
body:
  - type: checkboxes
    attributes:
      label: 必填确认项
      description: 提交前请确认以下内容
      options:
        - label: "此优化不在 [Issue](https://github.com/Pearl-Luo/Tianyicraft/issues) 和 [Pull request](https://github.com/Pearl-Luo/Tianyicraft/pulls) 列表中"
          required: true
        - label: "此优化在最新版本尚未实现并且更新我已为最新版本"
          required: true
        - label: "天依知道可以提出的优化太多啦，本人还是一个高一生忙不过来...所以我有足够的耐心等待本人的处理啦...催促这个 Issue 可能会被直接关闭哦！"
          required: true

  - type: textarea
    attributes:
      label: 描述建议
      placeholder: "清晰说明你的优化建议"
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: Minecraft 平台
      options:
        - "请选择"
        - "Java 版"
        - "基岩版"
        - "Java 版、基岩版"
    validations:
      required: true
