name: "建议 "
description: 一些好的建议都可以留下！
title: "[建议] "
labels: [优化, 等待审核]
body:
  - type: checkboxes
    attributes:
      label: 必填确认项
      description: 提交前请确认以下内容
      options:
        - label: "我已搜索现有Issue或Pull request，确认这一建议没有人提交过"
          required: true
        - label: "此建议在最新版本尚未实现并且更新我已为最新版本"
          required: true
        - label: "过于简单的且无法清晰描述的Issue可能会直接关闭"
          required: true

  - type: textarea
    attributes:
      label: 描述建议
      placeholder: "清晰说明你的建议"
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: Minecraft平台
      options:
        - "请选择"
        - "Java版"
        - "基岩版"
        - "Java版、基岩版"
    validations:
      required: true
