name: "建议 "
description: 一些好的建议都可以留下！
title: "[建议] "
labels: [可用于改善]
body:
  - type: checkboxes
    attributes:
      label: 必填确认项
      description: 提交前请确认以下内容
      options:
        - label: "我已搜索现有 Issue，未找到相同建议"
          required: true
        - label: "此建议在最新版本尚未实现"
          required: true
        - label: "我已将资源包更新为最新版本"
          required: true
        - label: "过于简单的且无法清晰描述的Issue可能会直接关闭"
          required: true

  - type: textarea
    attributes:
      label: 描述建议
      placeholder: "清晰说明你的建议"
    validations:
      required: true

  # 新增平台版本选择字段（必填）
  - type: dropdown
    attributes:
      label: Minecraft 平台
      options:
        - "请选择"
        - "Java 版"
        - "基岩版"
    validations:
      required: true  # 强制用户必须选择
